name: Ubuntu Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build
  CMAKE_C_COMPILER: gcc-13
  CMAKE_CPP_COMPILER: g++-13

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.296.0
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        stripdown: true

    - name: Install GCC 13
      run: sudo apt-get update && sudo apt-get -y install g++-13

    - name: Install Ninja
      run: sudo apt install ninja-build

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -D CMAKE_C_COMPILER=/usr/bin/gcc-13 -D CMAKE_CXX_COMPILER=/usr/bin/g++-13 -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Run Core Unit Tests
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --target run_core_tests